### ISSUE TITLE
stsprite not linking properly

### ISSUE THREAD

**Issue by gameblabla** [simonsunnyboy/stlibs4gcc#2]
It would appear that stsprite is not linking properly
```
stsprite_kernel.o:stsprite_kernel.o:(.text+0xfa): undefined reference to `STFM Sprite Kernel by Paradize v1.00 (gcc version)'
stsprite_kernel.o:stsprite_kernel.o:(.text+0x124): undefined reference to `nrsprites'

```

I removed STFM Sprite Kernel by Paradize v1.00 (gcc version) and changed nrsprites to nr_sprites, and that compiled it.
Unfortunately, as soon as i'm using the CPU drawing code (the example provided with it), it crashes upon calling STSprite_DrawCPU

**Comment by simonsunnyboy** [comment]
Verified. Fix pushed for the assembly symbols problem.

Calling with the complete kernel via STSprite_HandleDrawing() should work. 
Fix for the single sprite drawing is still pending.

**Comment by simonsunnyboy** [comment]
Stack frame access was bogus, explanation can be found at https://www.atari-forum.com/viewtopic.php?f=68&t=42705

Fix commited in assembly source

**Comment by gameblabla** [comment]
Thank you for looking into it !

**Comment by simonsunnyboy** [comment]
> Thank you for looking into it !

Thank you for reporting it! I never expected feedback here.

If you make some game/demo for the ST with those sources, please let me know.

I am open to give help if needed.
